<script setup lang="ts">
import { provide } from 'vue'
import Theme from 'vitepress-theme-neptu'
import {
  NavSearchButton,
  PageFindSearch,
} from 'vitepress-theme-neptu/components'
import { posts } from 'virtual:neptu-posts-data'

// Post data for every locale, handed to the theme through `provide`.
// The `virtual:neptu-posts-data` module is auto-generated by the theme's
// Vite plugin — it discovers every locale folder under `src/` that has a
// `_site.yaml` (or `_site.ts`) and a `loadPosts.data.ts`, then statically
// imports each data loader. No manual editing needed when adding a locale.
provide('posts', posts)

const { Layout } = Theme
</script>

<template>
  <Layout>
    <!-- Search button in the top bar. Remove this slot to drop the search UI. -->
    <template #nav-bar-content-before>
      <PageFindSearch>
        <NavSearchButton />
      </PageFindSearch>
    </template>
  </Layout>
</template>
