import fs from 'node:fs'
import path from 'node:path'

import { hasLocaleSite } from './i18n.ts'

// Inline interfaces so we do not need an explicit `vite` dependency.
// VitePress bundles vite, so at runtime the types match.
interface ResolveIdOptions {
  isEntry?: boolean
}

interface VirtualModulePlugin {
  name: string
  enforce: 'pre'
  resolveId(id: string, importer: string | undefined, options: ResolveIdOptions): { id: string } | null
  load(id: string): string | null
  configureServer(server: {
    watcher: {
      add(pattern: string | string[]): void
      on(event: string, handler: (filePath: string) => void): void
    }
    config: {
      logger: {
        error(msg: string): void
      }
    }
    restart(): Promise<void>
  }): void
  handleHotUpdate?(ctx: { file: string; server: { restart(): Promise<void> } }): void | Promise<void>
}

/**
 * Virtual module id — imported by `Layout.vue` as:
 *
 * ```ts
 * import { posts } from 'virtual:neptu-posts-data'
 * ```
 *
 * The plugin generates static `import { data } from '.../loadPosts.data'`
 * lines for every locale folder that contains a `_site.yaml` (or `_site.ts`)
 * and a `loadPosts.data.ts` file, then re-exports them as a single
 * `Record<localeIndex, PostLite[]>` object.
 *
 * This eliminates the manual step of editing `Layout.vue` every time a new
 * locale is added — the VitePress data-loader plugin only intercepts static
 * imports, so the virtual module bridges that gap with generated code.
 */
export const VIRTUAL_MODULE_ID = 'virtual:neptu-posts-data'
const RESOLVED_MODULE_ID = `\0${VIRTUAL_MODULE_ID}`

/** Name of the data-loader file inside each locale folder. */
const LOAD_POSTS_DATA_FILE = 'loadPosts.data.ts'

export interface PostsDataPluginOptions {
  /** Absolute path to the content source directory (same as `config.srcDir`). */
  srcDir: string
}

/**
 * Scans `srcDir` for locale folders and returns their names sorted
 * alphabetically. A folder qualifies when it contains `_site.yaml` or
 * `_site.ts` **and** a `loadPosts.data.ts` file.
 */
function discoverLocaleDataLoaders(srcDir: string): string[] {
  if (!srcDir || !fs.existsSync(srcDir)) return []

  const entries = fs.readdirSync(srcDir, { withFileTypes: true })
  const locales: string[] = []

  for (const entry of entries) {
    if (!entry.isDirectory()) continue
    if (entry.name.startsWith('.') || entry.name.startsWith('_')) continue
    if (!hasLocaleSite(srcDir, entry.name)) continue

    const dataFile = path.join(srcDir, entry.name, LOAD_POSTS_DATA_FILE)
    if (!fs.existsSync(dataFile)) continue

    locales.push(entry.name)
  }

  return locales.sort()
}

/**
 * Builds the virtual module source code: one static import per locale,
 * re-exported as a `posts` object whose keys match the folder names.
 */
function generateModuleSource(srcDir: string): string {
  const locales = discoverLocaleDataLoaders(srcDir)

  if (locales.length === 0) {
    // Return an empty object so the consuming code never crashes —
    // the theme will simply show no posts until a locale is set up.
    return 'export const posts: Record<string, { posts: unknown[] }[]> = {}\n'
  }

  const importLines: string[] = []
  const mapEntries: string[] = []

  for (const locale of locales) {
    const varName = `locale_${locale.replace(/[^a-zA-Z0-9]/g, '_')}_data`
    // Relative path from the project root — Vite resolves these at build time.
    // Using a relative path from srcDir keeps the module portable.
    const relPath = `./${locale}/${LOAD_POSTS_DATA_FILE}`
    importLines.push(
      `import { data as ${varName} } from '${relPath}'`
    )
    mapEntries.push(`  '${locale}': ${varName}.posts`)
  }

  return [
    `// Auto-generated by vitepress-theme-neptu:posts-data plugin.`,
    `// Do not edit — add or remove locale folders under srcDir instead.`,
    importLines.join('\n'),
    '',
    `export const posts = {`,
    mapEntries.join(',\n'),
    `}`,
  ].join('\n') + '\n'
}

/**
 * Vite plugin that provides the `virtual:neptu-posts-data` module.
 *
 * Scans `srcDir` at build/dev start, discovers every locale folder with a
 * `loadPosts.data.ts`, and generates a module that statically imports each
 * locale's data loader and re-exports them as a single `posts` object.
 *
 * This replaces the manual editing of `Layout.vue` when adding a locale.
 */
export function createPostsDataPlugin(
  options: PostsDataPluginOptions
): VirtualModulePlugin {
  const { srcDir } = options
  const absSrcDir = path.resolve(srcDir)

  return {
    name: 'vitepress-theme-neptu:posts-data',
    enforce: 'pre',

    resolveId(id: string): { id: string } | null {
      if (id === VIRTUAL_MODULE_ID) {
        return { id: RESOLVED_MODULE_ID }
      }
      return null
    },

    load(id: string): string | null {
      if (id === RESOLVED_MODULE_ID) {
        return generateModuleSource(absSrcDir)
      }
      return null
    },

    configureServer(server) {
      // Watch for locale folder additions/removals so the virtual module
      // regenerates when a new locale is created during dev.
      server.watcher.add([
        path.join(absSrcDir, '*/_site.yaml'),
        path.join(absSrcDir, '*/_site.ts'),
        path.join(absSrcDir, `*/${LOAD_POSTS_DATA_FILE}`),
      ])

      const onChange = (changedPath: string): void => {
        if (!changedPath.startsWith(absSrcDir)) return

        const baseName = path.basename(changedPath)
        if (
          baseName !== '_site.yaml' &&
          baseName !== '_site.ts' &&
          baseName !== LOAD_POSTS_DATA_FILE
        ) {
          return
        }

        // The virtual module content depends on which locale folders exist,
        // so a restart is needed to re-scan and regenerate the imports.
        server.restart().catch((error: Error) => {
          server.config.logger.error(
            `[neptu-blog] Failed to restart dev server: ${error.message}`
          )
        })
      }

      server.watcher.on('add', onChange)
      server.watcher.on('unlink', onChange)
    },
  }
}
