import { useData } from 'vitepress'
import { watchEffect } from 'vue'

interface LocaleWithDir {
  dir?: string
}

/**
 * Reactively sets `dir` on `<html>` based on the current locale's `dir` field.
 *
 * Handles client-side navigation. For the initial load (SSR / first paint),
 * a head script generated by `createDirHeadScript` sets the attribute before
 * the stylesheet is applied to avoid a flash.
 */
export function useLocaleDir(): void {
  const { site, localeIndex } = useData()

  watchEffect(() => {
    const locale = site.value.locales[localeIndex.value] as LocaleWithDir | undefined
    const dir = locale?.dir

    if (dir && dir !== 'auto') {
      document.documentElement.setAttribute('dir', dir)
    } else {
      document.documentElement.removeAttribute('dir')
    }
  })
}
